[package]
name = "scx-synse-helper"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "scx-synse-helper"
path = "src/main.rs"

[lib]
name = "scx_synse_helper"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1"
scx-synse-ipc = { path = "../scx-synse-ipc" }
rkyv = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
zbus = { workspace = true }
scx_loader = { workspace = true }
toml = "1"

[dev-dependencies]
tempfile = "3"
